# gcloud ai custom-jobs create \
#      --region=europe-west4 \
#      --display-name=test-run \
#      --config=gcloud_configs/config_gpu.yaml


workerPoolSpecs:
#    machineSpec:
#        machineType: n1-standard-8
#        acceleratorType: NVIDIA_TESLA_V100
#        acceleratorCount: 1
    machineSpec:
      machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
        imageUri: gcr.io/mlops/land-use-1
