name: "Run tests"

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Cache dependencies
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Download cached data artifact
    - name: Download cached data
      uses: actions/download-artifact@v2
      with:
        name: data
        path: Data/

    # Get data using DVC
    - name: Get data
      run: dvc pull
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

    # Upload data as an artifact
    - name: Cache data
      uses: actions/upload-artifact@v2
      with:
        name: data
        path: Data/

    # Test with pytest
    - name: Test with pytest
      run: |
        pip install pytest
        pytest -v
