name: "Run tests"

on:
  push:
    branches: [master, main, peetz-safe]
  pull_request:
    branches: [master, main, peetz-safe]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Cache dependencies
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pyopenssl
        pip install -r requirements.txt

    # Get data using DVC
    - uses: iterative/setup-dvc@v1
    - name: Get data
      run: dvc pull -v
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

    # Download cached data artifact
    - name: Download cached data
      uses: actions/download-artifact@v2
      with:
        name: data
        path: Data/

    # Test with pytest
    - name: Test with pytest
      run:
        pytest tests
