name: "Run tests 2"

on:
  push:
    branches: [master, main, peetz-safe]
  pull_request:
    branches: [master, main, peetz-safe]
jobs:
  test:
    name: Run pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.9
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install --upgrade dvc


      - name: Download data
        run: dvc pull -v
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
    # Test with pytest
      - name: Test with pytest
        run:
          pytest tests
