name: "Run tests"

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10.11
        cache: 'pip'
    # Cache dependencies
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pyopenssl
        pip install -r requirements.txt

    # Download cached data artifact
    - name: Download cached data
      uses: actions/download-artifact@v2
      with:
        name: data
        path: Data/

    # Get data using DVC
    - uses: iterative/setup-dvc@v1
    - name: Get data
      run: dvc pull -v
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

    # Test with pytest
    - name: Test with pytest
      run:
        pytest tests
